/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import DataClasses.Location;
import bl.LLM;

/**
 *
 * @author fabia
 */
public class DestinationDlg extends javax.swing.JDialog
{

  private Location loc;

  public Location getLoc()
  {
    return loc;
  }

  public DestinationDlg(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    tfCountry = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    tfCity = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridLayout(3, 2));

    jLabel1.setText("Country");
    getContentPane().add(jLabel1);

    tfCountry.setToolTipText("");
    getContentPane().add(tfCountry);

    jLabel3.setText("Cityname");
    getContentPane().add(jLabel3);
    getContentPane().add(tfCity);

    jButton1.setText("Add");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAdd(evt);
      }
    });
    getContentPane().add(jButton1);

    jButton2.setText("Discare");
    jButton2.setToolTipText("");
    getContentPane().add(jButton2);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onAdd(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAdd
  {//GEN-HEADEREND:event_onAdd
    String country = tfCountry.getText();
    String name = tfCity.getText();
    
    loc = new Location(country,name);

    dispose();
  }//GEN-LAST:event_onAdd

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(DestinationDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(DestinationDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(DestinationDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(DestinationDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        DestinationDlg dialog = new DestinationDlg(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField tfCity;
  private javax.swing.JTextField tfCountry;
  // End of variables declaration//GEN-END:variables
}
